
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Dashboard_New.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CHECKDRAWN
{

    public string PARTY { get; set; }

    public System.DateTime CQDATE { get; set; }

    public string CHEQ_NO { get; set; }

    public string RPTWRD { get; set; }

    public double RSAMT { get; set; }

    public string AUTH1 { get; set; }

    public string AUTH2 { get; set; }

    public string VOUCHNO { get; set; }

    public string BRNO { get; set; }

    public string AUTH { get; set; }

    public string ADJ { get; set; }

    public string PRINT { get; set; }

    public string CHECK { get; set; }

    public string NPRNO { get; set; }

    public string ICCNO { get; set; }

    public string INSTID { get; set; }

    public string STATUS { get; set; }

    public string EMAILID { get; set; }

    public string PARTYCODE { get; set; }

    public string option_val { get; set; }

    public string CHEK { get; set; }

}

}
