
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Dashboard_New.Models
{

using System;
    using System.Collections.Generic;
    
public partial class DVOUCH
{

    public System.DateTime DINP { get; set; }

    public string DCTRNO { get; set; }

    public string AMOUNT { get; set; }

    public string NPRNO { get; set; }

    public string ICCNO { get; set; }

    public string COMNO { get; set; }

    public string VRNO { get; set; }

    public string BRNO { get; set; }

    public string DCID { get; set; }

    public string ASSTCK { get; set; }

    public string ACCTCK { get; set; }

    public string ACCT1CK { get; set; }

    public string SOCK { get; set; }

    public string DRCK { get; set; }

    public Nullable<System.DateTime> CRDATE { get; set; }

    public string DCTRBNO { get; set; }

    public string LUSER { get; set; }

}

}
