//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard_New.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class indent_master
    {
        public string indent_no { get; set; }
        public string dept { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> indent_date { get; set; }
        public string purch_desc { get; set; }
        public string category { get; set; }
        public Nullable<double> indent_value { get; set; }
        public Nullable<decimal> IndentValueRs { get; set; }
        public string cocode { get; set; }
        public string gcode { get; set; }
        public string currency { get; set; }
        public string IndentType { get; set; }
        public string status { get; set; }
        public string remarks { get; set; }
    }
}
