
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Dashboard_New.Models
{

using System;
    using System.Collections.Generic;
    
public partial class MSTLST
{

    public string NPRNO { get; set; }

    public string TITLE { get; set; }

    public string COOR_NAME { get; set; }

    public Nullable<System.DateTime> START_DATE { get; set; }

    public Nullable<System.DateTime> CLOSE_DATE { get; set; }

    public double PRAMOUNT { get; set; }

    public string SANCTNNO { get; set; }

    public Nullable<System.DateTime> SANCTDTE { get; set; }

    public string INSTID { get; set; }

    public string COOR_NAME1 { get; set; }

    public string INSTID1 { get; set; }

    public string USERNAME { get; set; }

    public string ACCOUNTTYPE { get; set; }

}

}
