//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard_New.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REC1718
    {
        public Nullable<System.DateTime> DINP { get; set; }
        public string RTNO { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string SPONS { get; set; }
        public string ADDRESS { get; set; }
        public string SANCTNO { get; set; }
        public double PRAMOUNT { get; set; }
        public double CONAMOUNT { get; set; }
        public double OTRAMOUNT { get; set; }
        public double RT { get; set; }
        public double AMOUNT { get; set; }
        public string HEAD { get; set; }
        public string NPRNO { get; set; }
        public string ICCNO { get; set; }
        public string CQNO { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public string BANKNAME { get; set; }
        public string BRANCH { get; set; }
        public string STATION { get; set; }
        public string OPTION { get; set; }
        public string BK_OPT { get; set; }
        public string BK_ADJ { get; set; }
        public string NATURE { get; set; }
        public string CURYNAME { get; set; }
    }
}
