//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard_New.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class useraccount
    {
        public string Name { get; set; }
        public string Designation { get; set; }
        public string Section { get; set; }
        public string Process { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string UserType { get; set; }
    }
}
