//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard_New.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorMaster
    {
        public System.DateTime DINP { get; set; }
        public string VPartyCode { get; set; }
        public string VName { get; set; }
        public string VAddress { get; set; }
        public string VPinCode { get; set; }
        public string VMobile { get; set; }
        public string VPhoneNumber { get; set; }
        public string VEmailId { get; set; }
        public string VPanNo { get; set; }
        public string VTinNo { get; set; }
        public string VSerTaxRegNo { get; set; }
        public string VAcctNameInBank { get; set; }
        public string VBankName { get; set; }
        public string VBranchName { get; set; }
        public string VIFSCCode { get; set; }
        public string VBankAcctNo { get; set; }
        public string VBankNature { get; set; }
        public string VBankMICRCode { get; set; }
        public string VBankPhoneNumber { get; set; }
        public string VBankEmailID { get; set; }
        public string Luser { get; set; }
    }
}
